Assignment 1

In [1]:
from google.colab import files
uploaded = files.upload()

Saving data-27.csv to data-27.csv

In [4]:
import pandas as pd

In [6]:
df = pd.read_csv('data-27.csv')
df.head()

,datetime,open,high,low,close,volume,Unnamed: 0.1,Unnamed: 0
0,2018-01-01 00:00:00,13715.65,13818.55,12750.00,13135.00,6970.441076,NaN,NaN
1,2018-01-02 00:00:00,13135.00,14750.00,12890.02,14580.00,16359.347340,NaN,NaN
2,2018-01-03 00:00:00,14576.87,15473.49,14150.00,14749.97,19457.238601,NaN,NaN
3,2018-01-04 00:00:00,14710.00,15280.00,13918.04,14811.00,18783.876561,NaN,NaN
4,2018-01-05 00:00:00,14805.01,17118.13,14600.00,16579.00,22383.657333,NaN,NaN

PART 1

In [7]:
print("Shape of the dataset:", df.shape)

print("\nColumns in dataset:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nSummary Statistics:")
print(df.describe())

print("\nMissing Values in each column:")
print(df.isnull().sum())

Shape of the dataset: (2924, 8)

Columns in dataset:
Index(['datetime', 'open', 'high', 'low', 'close', 'volume', 'Unnamed: 0.1',
       'Unnamed: 0'],
      dtype='object')

Data Types:
datetime         object
open            float64
high            float64
low             float64
close           float64
volume          float64
Unnamed: 0.1    float64
Unnamed: 0      float64
dtype: object

Summary Statistics:
               open          high           low         close         volume  \
count   2924.000000   2924.000000   2924.000000   2924.000000    2924.000000
mean   18155.724839  18623.465082  17641.735393  18163.987353   67925.306605
std    15226.458730  15623.722788  14779.220733  15235.053085   76479.022079
min     3183.900000   3281.870000   3156.260000   3182.730000    3367.160695
25%     7202.790000   7408.750000   7017.480000   7202.960000   30075.857572
50%    10191.480000  10445.000000   9890.000000  10186.600000   43493.845601
75%    27272.127500  27817.137500  26812.465000  27321.242500   69989.787196
max    67525.820000  69000.000000  66222.400000  67525.830000  760705.362783

       Unnamed: 0.1   Unnamed: 0
count   2193.000000  2193.000000
mean    1096.000000  1096.000000
std      633.208891   633.208891
min        0.000000     0.000000
25%      548.000000   548.000000
50%     1096.000000  1096.000000
75%     1644.000000  1644.000000
max     2192.000000  2192.000000

Missing Values in each column:
datetime          0
open              0
high              0
low               0
close             0
volume            0
Unnamed: 0.1    731
Unnamed: 0      731
dtype: int64

In [9]:
df['SMA'] = df['close'].rolling(window=20).mean()

df['EMA_20'] = df['close'].ewm(span=20, adjust=False).mean()
df['EMA_50'] = df['close'].ewm(span=50, adjust=False).mean()

df[['close', 'SMA', 'EMA_20', 'EMA_50']].head(30)

       close         SMA        EMA_20        EMA_50
0   13135.00         NaN  13135.000000  13135.000000
1   14580.00         NaN  13272.619048  13191.666667
2   14749.97         NaN  13413.319138  13252.776601
3   14811.00         NaN  13546.431601  13313.883401
4   16579.00         NaN  13835.247639  13441.927189
5   16769.89         NaN  14114.737388  13572.435535
6   16019.25         NaN  14296.119541  13668.389043
7   14900.00         NaN  14353.631966  13716.687512
8   14803.44         NaN  14396.470826  13759.305257
9   14548.32         NaN  14410.932653  13790.247012
10  13661.50         NaN  14339.558114  13785.198109
11  13405.28         NaN  14250.579246  13770.299360
12  14259.37         NaN  14251.416461  13789.478601
13  13265.00         NaN  14157.472036  13768.910812
14  13827.95         NaN  14126.088985  13771.226075
15  10993.18         NaN  13827.716701  13662.283091
16   9650.00         NaN  13429.838920  13504.938656
17  11465.00         NaN  13242.711403  13424.941062
18  11185.10         NaN  13046.748413  13337.104158
19  13035.00  13782.1625  13045.629516  13325.256936
20  11344.57  13692.6410  12883.623848  13247.582938
21  10399.81  13483.6315  12647.070148  13135.905568
22  11200.00  13306.1330  12509.253944  13059.987703
23  11069.09  13119.0375  12372.095473  12981.913283
24  11250.00  12852.5875  12265.229237  12913.995115
25  11033.00  12565.7430  12147.874072  12840.230601
26  11485.00  12339.0305  12084.743208  12787.084303
27  11783.00  12183.1805  12056.005759  12747.708448
28  11379.02  12011.9595  11991.530925  12694.034391
29  10073.79  11788.2330  11808.888932  12591.279709

PART 2

In [13]:
df['date'] = pd.to_datetime(df['datetime'])

df.set_index('date', inplace=True)

df.head()

,datetime,open,high,low,close,volume,Unnamed: 0.1,Unnamed: 0,SMA,EMA_20,EMA_50
date,,,,,,,,,,,
2018-01-01,2018-01-01 00:00:00,13715.65,13818.55,12750.00,13135.00,6970.441076,NaN,NaN,NaN,13135.000000,13135.000000
2018-01-02,2018-01-02 00:00:00,13135.00,14750.00,12890.02,14580.00,16359.347340,NaN,NaN,NaN,13272.619048,13191.666667
2018-01-03,2018-01-03 00:00:00,14576.87,15473.49,14150.00,14749.97,19457.238601,NaN,NaN,NaN,13413.319138,13252.776601
2018-01-04,2018-01-04 00:00:00,14710.00,15280.00,13918.04,14811.00,18783.876561,NaN,NaN,NaN,13546.431601,13313.883401
2018-01-05,2018-01-05 00:00:00,14805.01,17118.13,14600.00,16579.00,22383.657333,NaN,NaN,NaN,13835.247639,13441.927189

In [18]:
volatility = df['close'].resample('6M').std()

print("🔹 6-Month Standard Deviations:\n")
print(volatility)

🔹 6-Month Standard Deviations:

date
2018-01-31     2015.271600
2018-07-31     1328.840791
2019-01-31     1407.786648
2019-07-31     2798.572026
2020-01-31     1312.245827
2020-07-31     1372.755043
2021-01-31     8741.749329
2021-07-31    10029.363786
2022-01-31     7837.139102
2022-07-31     8890.239310
2023-01-31     2336.555334
2023-07-31     2736.763731
2024-01-31     6386.320742
Freq: 6ME, Name: close, dtype: float64

<ipython-input-18-5cff5bc504e1>:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  volatility = df['close'].resample('6M').std()

In [19]:
most_volatile_period = volatility.idxmax()
highest_std = volatility.max()

print("\nMost Volatile 6-Month Period:")
print(f"Start of Period: {most_volatile_period.strftime('%Y-%m-%d')}")
print(f"Standard Deviation: {highest_std:.2f}")

Most Volatile 6-Month Period:
Start of Period: 2021-07-31
Standard Deviation: 10029.36